excerpt_separator: ""
pygments: true
theme: minima
markdown: kramdown
url: http://priimak.github.io
title: Meaningful Notes in Meaningless World.
tagline: 
description: Blog related to science, software and ...
paginate: 5
